### ISSUE TITLE
somerhing wrong with the hacking game

### ISSUE THREAD

**Issue by olegend965** [qbcore-framework/qb-prison#10]
I tryed to the minigame that are near the big gate, after a success attempt it didn't open.

I got no idea how to fix it. ^^

**Comment by pushkart2** [comment]
This issue is similar to the fix that I did for bankrobbery and doors.
whenever you complete the hack, the door id is wrong.. so see the exact door id, which can be done using a simple print statement in qb-doorlock and update it here
`local Gates = {
    [1] = {
        gatekey = 38,
        coords = vector3(1845.99, 2604.7, 45.58),
        hit = false,
    },
    [2] = {
        gatekey = 39,
        coords = vector3(1819.47, 2604.67, 45.56),
        hit = false,
    },
    [3] = {
        gatekey = 40,
        coords = vector3(1804.74, 2616.311, 45.61),
        hit = false,
    }
}
`

**Comment by Developer-Bear** [comment]
Couldn't reproduce this issue

**Comment by vanillla1** [comment]
fix your issues
https://github.com/qbcore-framework/qb-prison/pull/12
https://github.com/qbcore-framework/qb-doorlock/pull/14
