### ISSUE TITLE
/jail dont seem to work[BUG]

### ISSUE THREAD

**Issue by Thehoodedslayers** [qbcore-framework/qb-prison#100]
**Describe the bug**
so i have noticed the last week or so we been getting alot of tickets about the jail system and ive looked in to seeing if anything was causing this and couldn't see anything but to be on the safe side i have downloaded a fresh copy of qb-prison and qb-police job and /jail is still not working it brings up how long to send the person off but once chosen it does not do anything. ive had no issue b4

**Comment by TomTheDark** [comment]
The same for me

**Comment by GhzGarage** [comment]
Latest version has been tested and working
