### ISSUE TITLE
Problems that must be resolved

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-prison#22]
When the player is sent to prison, all the items he has will disappear
But when he gets out of prison, the items that were removed from him before entering prison return to him
The problem is that if he obtains items inside the prison, such as food, drink, or other gifts from the prisoners, the code inside the prison deletes the items he obtained from the prison and gives him the items that were taken from him before entering the prison.
The return of the elements must be in addition, not the erasure and addition
For example, suppose the player takes lockpick 
From another player before leaving prison to take a car and go to the city
Here it is a big problem
Because the prison will wipe the items before getting out of prison
This is not logical

Sometimes it is not erased metadata The player is out of prison
A good scanning mechanism should be put into the values inside metadata

**Comment by evanillaa** [comment]
I hope these problems are resolved quickly
I tried to add the items that the player got from prison
But unfortunately I couldn't

**Comment by evanillaa** [comment]
https://ibb.co/Zfd3BZp
https://ibb.co/GtWsxN1

**Comment by evanillaa** [comment]
and review this please
TriggerServerEvent("prison:server:SetJailStatus", 0)
Why does it sometimes not work?

**Comment by evanillaa** [comment]
I am working on solving prison problems
There is a new problem
  1. When escaping from prison, the items that were taken from you before entering prison will not return to you. This is good for now.
2. But assuming that the player entered prison after two or three days and his personal items were withdrawn from him before imprisonment, and assuming that he was released naturally from prison
The items that were withdrawn from him two days ago will be returned to him in case No. 1, but the items that were withdrawn from him will be returned to him in the second case

**Comment by SamShanks1** [comment]
Fixed in #26
