### ISSUE TITLE
Prison Freedom doesnt work....

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-prison#25]
When ever you send someone to jail they cant use the freedom

**Comment by SamShanks1** [comment]
Unable to replicate issue

**Comment by Kromanic** [comment]
so normally when ur time is up u go to a certain location to click for you are able to fly out... well the food location and checking out location doesn't promp you to see or do anything.... i personally have to unjail them cause they cant get out by them self

**Comment by WolfieValeo** [comment]
So i stumbled across this issue today, I had someone who was sent in did their time but the freedom thing didnt work no text or prompt, i then had to manually unjail them to get them out but they lost all their items. i tried to replicate it on myself and had the same result 3 times.
