### ISSUE TITLE
[FEATURE REQUEST] Prisoner Death Respawn Location

### ISSUE THREAD

**Issue by GLaZeD-DoHNuTz** [qbcore-framework/qb-prison#31]
Is your feature request related to a problem? Please describe.

--> If someone dies in prison, they spawn at Pillbox instead of the prison hospital

Describe the feature you'd like

--> The feature if it isn't implemented already, would be if a prisoner dies, then they would respawn in the prison hospital 

Additional context

--> None, but I can take a clip if neccessary!

**Comment by Neaw92** [comment]
Same exact issue, just placed a safe zone down to counteract this.

**Comment by GLaZeD-DoHNuTz** [comment]
@Neaw92 Can you send me how you did that?
