### ISSUE TITLE
Death respawns at Hospital

### ISSUE THREAD

**Issue by Gambrino** [qbcore-framework/qb-prison#72]
Players have been abusing this system by having themselves killed then spawn at the Hospital.

**Comment by TheOldHook** [comment]
A simple solution to your problem, add this to your main client file on all the needed events:
```
	local player = GetPlayerPed(-1)
	SetPlayerInvincible(PlayerId(), true)
```
This enables god mode on the player, when you add it on the three events the godmode will go away once unjailed or time is done.

**Comment by Gambrino** [comment]
> local player = GetPlayerPed(-1)
> 	SetPlayerInvincible(PlayerId(), true)

I really appreciate it, where do I add this?

**Comment by BerkieBb** [comment]
Don't use GetPlayerPed(-1) ever

**Comment by BerkieBb** [comment]
Oh I see what you mean, in the rewrite I'll add an infirmary for the prison if I can get something like that with a map
