### ISSUE TITLE
[BUG] 3rd eye, spawns.

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-prison#75]
**Describe the bug**
using the latest version.

**To Reproduce**
1. Go to 'prison shop or freedom ped, 3rd eye not working '
2. when sent to jail its sending you outside. not in the preset places. 
3. Click on '....'
4. Use this item '....' (item's name from shared.lua if applicable)
5. See error no errors

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by BerkieBb** [comment]
Fixed the ped issue but the third eye issue is what I couldn't reproduce, it works fine for me

**Comment by BerkieBb** [comment]
And the outside spawn is fine as well, it takes it from the config

**Comment by Andyauk** [comment]
> Fixed the ped issue but the third eye issue is what I couldn't reproduce, it works fine for me

strange as i set it back to target off, and its fine. but with it on. it don't work. ill try the pr you did. thanks
