### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sizan19** [qbcore-framework/qb-prison#83]
**Describe the bug**
While jailing someone some random people goes directly jailbreak not all and gets kicked out of prison .

**To Reproduce**
1. jail someone
2. some people is sent directly to jailbreak 
3. but it doesnt happens all the time 

**Expected behavior**
--

**Screenshots**
---

**Questions (please complete the following information):**
 - When you last updated: [ last week]
 - Are you using custom resource? which ones? [everything is qbus]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**
While jailing someone some random people goes directly jailbreak not all and gets kicked out of prison .

**Comment by BerkieBb** [comment]
Could you show a video of what you mean because I don't get it

**Comment by sizan19** [comment]
> Could you show a video of what you mean because I don't get it

while you leave the polyzone of prison it makes it as jailbreak . if your asset is not loaded u will fall and it will cause jailbreak

**Comment by BerkieBb** [comment]
That's the expected feature, that's how it's supposed to be

**Comment by BerkieBb** [comment]
But I can change it to only affect x and y instead of also z, so that should solve your issue
