### ISSUE TITLE
[BUG] Inventory Duplication on Prison Exit

### ISSUE THREAD

**Issue by Wandorf** [qbcore-framework/qb-prison#85]
**Describe the bug**
When a player goes to leave the jail using E and spams the key it causes their inventory to duplicate.

**To Reproduce**
1. Wait for sentence to expire.
2. Spam E to leave prison
3. Inventory duplicates

**Expected behavior**
When leaving prison any amounts of key presses should only give the items they went in with.

**Screenshots**
https://cdn.discordapp.com/attachments/928520398138654790/990068358554722344/unknown.png

**Questions (please complete the following information):**
 - When you last updated: Today (June 24 2022
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Comment by k2xp** [comment]
try change it to a ped where players get the items back and use target for execution...
