### ISSUE TITLE
how can we add jail uniforms?[SUGGESTION]

### ISSUE THREAD

**Issue by LightUpFam** [qbcore-framework/qb-prison#93]
how can we add jail uniforms? would enhance rp alot

**Comment by nzkfc** [comment]
Came here to suggest this :)

**Comment by tom-osborne** [comment]
Prisoner uniforms were added here: https://github.com/qbcore-framework/qb-prison/pull/94

**Comment by LightUpFam** [comment]
i took same function code and used it for the ambulance job as well so when you die or get revived you get put into hospital clothes

**Comment by tom-osborne** [comment]
> i took same function code and used it for the ambulance job as well so when you die or get revived you get put into hospital clothes

@LightUpFam want to create a PR for that? 👀
