### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Ovi32** [qbcore-framework/qb-prison#96]
**Describe the feature you'd like**
People should get their original cloth back after release from prison.Currently it keep the prison dress after bail

**Comment by OMikkel** [comment]
Have you tried updating to the latest files, try backing up the old folder on your server and then git clone this repo into your resources folder.

I just tested it and with the latest files it works, if you haven't modified the `qb-clothes:loadPlayerSkin` event. 
[This line](https://github.com/qbcore-framework/qb-prison/blob/main/client/main.lua#L300) should do the trick and load in your normal player skin after you have served your time.
https://github.com/qbcore-framework/qb-prison/blob/main/client/main.lua#L300
