### ISSUE TITLE
[BUG] Gatecrack not been working for months?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-prison#97]
**Describe the bug**
No interaction with the prison gates using gatecrack, electronickit seems to do anything with the gates.

**To Reproduce**
1. Have gatecrack/electronickit on you
2. Go to gate and try use them
3. ???

**Expected behavior**
Minigame should appear after a progressbar to hack the gates

**Screenshots**
Video: https://youtu.be/hQXa7nCbR3o

**Questions (please complete the following information):**
 - When you last updated: 1 hour ago
 - Are you using custom resource? which ones? Lots but nothing affecting prison
 - Have you renamed `qb-` to something custom? Nope

**Additional context**
I noticed a few months ago that people couldn't crack the gate, on looking at it I couldn't work it out either, we were on nui-doorlocks so I moved us over to qb-doorlocks and still the prison gates don't do anything (but are locked) and it's all running off the default gate locks in config.lua in qb-doorlock. We have not set any locks there in the /configs/ folder or anything like that.

When I updated just now, I noticed a lot of new door lock events etc coming back into the script, so I thought it was fixed and someone accidently removed it from the qb team months ago by mistake or something, but on using it again, still can't do anything with the gates?

**Comment by Sharkiiie** [comment]
So I'm looking through all your issues because you post good ones unlike the majority of the other issues lmao

I tested this with a fresh server and it seems to be working fine.

**Comment by nzkfc** [comment]
Haha what can I say, I usually test fresh first then post.

I will pull a fresh and test again then compare doorlock and prison against
fresh and see what's diff.

BTW might be better to move the default banks/prison config to their own
individual lua as it can be confusing using config.lua and then setting new
ones in /configs/

**Comment by Sharkiiie** [comment]
Thing is it doesn't look like the prisonbreak had any updates after this issue was posted, so not sure why it wouldn't be working on your version.

Not sure what you mean by the config issue. 
Could move the gates to the config? but prion just has a config.lua
bankrobbery should prolly move them to a config folder because its ugly right now

**Comment by nzkfc** [comment]
> Thing is it doesn't look like the prisonbreak had any updates after this issue was posted, so not sure why it wouldn't be working on your version.
> 
> Not sure what you mean by the config issue. Could move the gates to the config? but prion just has a config.lua bankrobbery should prolly move them to a config folder because its ugly right now

So been looking into this a bit more, I pulled a fresh city again and tried it, worked fine.

So I pulled fresh qb-prison into my dev city and then even copied the gatecrack/electronickit items into items.lua to double check it's same-same and still doesn't work.

I'm not sure what else could be involved that would stop it from working? (we have no AC or anything on dev also)

**Comment by FrequencyRoleplay** [comment]
might be your dev city is older qbcore , and your fresh pull was the newer qbcore with server has item. 

im experiencing the same issue currently, an older version of qb prison may help

**Comment by Glen92** [comment]
Having the same issue and i have a newer qb core so i dont think that is the problem anyone found a fix?

**Comment by nzkfc** [comment]
Replace prison script :P
